management:
  security:
    enabled: false
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env,mappings,health,trace,beans,auditevents
spring:
  profiles: dev
server:
  port: 8000
---
spring:
  profiles: test
server:
  port: 9000